configurations:
  behavior.void:
    system_instruction: ""

  archive.markdown.experiments:
    type: "markdown"
    user_header: "### Silvestro :eyes:"
    ai_header: "### Chase :seedling:"
    to_present: false


  archive.markdown.experiments.01_blueprint_generation:
    directory_path: "./experiments/01_blueprint_generation"


  archive.markdown.experiments.02_detailed_spec_generation:
    directory_path: "./experiments/02_detailed_spec_generation"


  archive.markdown.experiments.03_json_conversion:
    directory_path: "./experiments/03_json_conversion"


  middleware.test_spec_json_validator:
    type: "test_spec_json_validator"



profiles:
  01_blueprint_generation:
    inference: "inference.quasi-deterministic.gemini_3_high_think"
    behavior: "behavior.void"
    provider: "provider.gemini.vertex.3-1-pro-preview"
    constraints: "constraints.standard"
    input_source: "io.input.variable"
    output_sink: "io.output.variable"
    archive: "archive.markdown.experiments.01_blueprint_generation"


  02_detailed_spec_generation:
    inference: "inference.quasi-deterministic.gemini_3_high_think"
    behavior: "behavior.void"
    provider: "provider.gemini.vertex.3-1-pro-preview"
    constraints: "constraints.standard"
    input_source: "io.input.variable"
    output_sink: "io.output.variable"
    archive: "archive.markdown.experiments.02_detailed_spec_generation"


  03_json_conversion:
    inference: "inference.quasi-deterministic.gemini_3_high_think"
    behavior: "behavior.void"
    provider: "provider.gemini.vertex.3-1-pro-preview"
    constraints: "constraints.standard"
    input_source: "io.input.variable"
    output_sink: "io.output.variable"
    archive: "archive.markdown.experiments.03_json_conversion"
    response_sanitization:
      - "middleware.json_fence_enforcer"
    post_response_normalization:
      - "middleware.json_code_block_tagger"
      - "middleware.json_escape_repair"
      - "middleware.test_spec_json_validator"
    presentation:
      - "middleware.json_fence_stripper"