configurations:

  behavior.void:
    system_instruction: ""


  archive.markdown.experiments:
    type: "markdown"
    user_header: "### Silvestro :eyes:"
    ai_header: "### Chase :seedling:"

  archive.markdown.experiments.01_repo_knowledge:
    directory_path: "./experiments/01_repo_knowledge"

  archive.markdown.experiments.02_api_contracts:
    directory_path: "./experiments/02_api_contracts"

profiles:

  01_repo_knowledge:
    inference: "inference.quasi-deterministic.gemini_3_high_think"
    behavior: "behavior.void"
    provider: "provider.gemini.vertex.3-1-pro-preview"
    constraints: "constraints.standard"
    input_source: "io.input.variable"
    output_sink: "io.output.variable"
    archive: "archive.markdown.experiments.01_repo_knowledge"

  02_api_contracts:
    inference: "inference.quasi-deterministic.gemini_3_high_think"
    behavior: "behavior.void"
    provider: "provider.gemini.vertex.3-1-pro-preview"
    constraints: "constraints.standard"
    input_source: "io.input.variable"
    output_sink: "io.output.variable"
    archive: "archive.markdown.experiments.02_api_contracts"

