import json
import env_setup

# ==========================================
# 1. DEPENDENCY MAPPING
# ==========================================
# Based exactly on the "Tier 3: Auxiliary: Third-Party" imports 
# generated by the LLM in the previous steps.
TEST_DEPENDENCIES = {
    "dataset": ["sqlalchemy"],
    "folium": ["pandas"],
    "imageio": ["numpy"],
    "lifelines": ["matplotlib", "numpy", "pandas"],
    "pyjwt": ["cryptography"],
    "requests": ["responses", "urllib3"],
    "schedule": ["freezegun"],
    "sqlmodel": ["pydantic", "sqlalchemy"],
    "stegano": ["Pillow"] # Note: 'import PIL' requires the 'Pillow' package
}

# ==========================================
# 2. UPDATE METADATA
# ==========================================
print("="*60)
print("STEP 1: Injecting Test Dependencies into Metadata")
print("="*60)

# We target the individual JSON files you created in the previous phase
metadata_files = list(env_setup.METADATA_DIR.glob("*.json"))
print(f"Found {len(metadata_files)} metadata files to update.\n")

updated_count = 0

for meta_file in metadata_files:
    project_name = meta_file.stem
    
    # Load the existing metadata
    with open(meta_file, "r", encoding="utf-8") as f:
        metadata = json.load(f)
        
    # Get the dependencies for this project (default to empty list if none)
    deps = TEST_DEPENDENCIES.get(project_name, [])
    
    # Inject the new field
    metadata["test_dependencies"] = deps
    
    # Save it back
    with open(meta_file, "w", encoding="utf-8") as f:
        json.dump(metadata, f, indent=2, ensure_ascii=False)
        
    if deps:
        print(f"  [UPDATED] {project_name.ljust(15)} | Added: {', '.join(deps)}")
    else:
        print(f"  [SKIPPED] {project_name.ljust(15)} | No extra dependencies needed.")
        
    updated_count += 1

print("\n" + "="*60)
print(f"[DONE] Successfully processed {updated_count} metadata files.")
print("="*60)